# Generated by Django 3.2.7 on 2021-12-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Python', models.CharField(max_length=30)),
                ('TOC', models.CharField(max_length=30)),
                ('DBMS', models.CharField(max_length=30)),
                ('OS', models.CharField(max_length=30)),
                ('SE', models.CharField(max_length=30)),
                ('ES', models.CharField(max_length=30)),
            ],
        ),
    ]
