# Generated by Django 3.2.7 on 2021-12-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student2', '0002_student_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_score',
            name='ES',
        ),
        migrations.RemoveField(
            model_name='student_score',
            name='SE',
        ),
    ]
